---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - argocd.repocreds.io
  resources:
  - argocdrepocreds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - argocd.repocreds.io
  resources:
  - argocdrepocreds/finalizers
  verbs:
  - update
- apiGroups:
  - argocd.repocreds.io
  resources:
  - argocdrepocreds/status
  verbs:
  - get
  - patch
  - update
